version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${USER} -d ${NAME}
      interval: 3s
      timeout: 3s
      retries: 10

  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
      PORT: 5432


volumes:
  pg_data:

