# Generated by Django 5.1.1 on 2024-10-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name'], 'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['name', 'breed'], 'verbose_name': 'Кот', 'verbose_name_plural': 'Коты'},
        ),
    ]
